# 1. Site Settings
title               : 垃圾箱
owner               : "垃圾残渣"
#url                 : "http://127.0.0.1:4000"
url                : "https://gmkz.top" # A trailing “/” at the end of the field is unnecessary.
## baseurl            : ""
permalink           : /:title/
description         : "Personal rubbish of gmkzwwg"
markdown            : kramdown
statement           : "Designed by gmkzwwg, All Rights Reserved"
bgtext              : "αβγδεζηθικλμνξοπρστυφχψω∝∞∑∏∪∩∈∵∴⊥∠⊙≌∽√∀∂∆∇⋈∅∫∬∳∯∱∲ℂℍℚℝℕℙℤⅈⅉⅇℼℽℵ" # texts randomly displayed in background
# bgtext              : "01"
# bgtext              : "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"


# 2. Collections
collection_order    : 
  [
    "phil",    
    "lit",
    "hist",
    "psyc",
    "math",
    "comp",
    "phys",
    "lang",
  ]

collections:
  math:
    output          : true
    permalink       : /:collection/:categories/:title/
    alias           : "MATH"
  phil:
    output          : true
    permalink       : /:collection/:categories/:title/
    alias           : "PHIL"
  hist:
    output          : true
    permalink       : /:collection/:categories/:title/
    sort_by         : name
    alias           : "HIST"
  lit:
    output          : true
    permalink       : /:collection/:categories/:title/
    alias           : "LIT"
  comp:
    output          : true
    permalink       : /:collection/:categories/:title/
    alias           : "COMP"
  lang:
    output          : true
    permalink       : /:collection/:categories/:title/
    alias           : "LANG"
  psyc:
    output          : true
    permalink       : /:collection/:categories/:title/
    alias           : "PSYC"
  phys:
    output          : true
    permalink       : /:collection/:categories/:title/
    alias           : "PHYS"

# 3. Comment settings（disqus.com）
disqus_username     : gmkzwwg

# 4. Default page configuration
defaults:
  -    
    scope:
      path          : ""  # an empty string here means all files in the project
    values:
      layout              : "post"      # which layout to use by default
      publish             : true        # whether to show by default      
      btn_text            : true        # whether show button text by default
      collection_list     : true        # whether show archive button by default
      home_btn            : true        # whether show home by default
      maximize            : true        # whether show maximize button by default
      encrypted_text      : false       # whether use encrytion function by default
      toc                 : true        # whether show table of content by default
      toc_depth           : 4           # the toc depth by default
      author              :             # author name by default
      show_date           : false       # whether show date message by default
      category            :             # category by default
      post_list           : false       # whether show list of post by default      
      comment             : false
      footer              : false       # whether show footer by default
      highlight           : false

# 5. Social Media Accounts
email               : "gmkzwwg@outlook.com" 
github              : "gmkzwwg" 

# 6. Where things are
source              : .
destination         : ./_site
collections_dir     : collections
plugins_dir         : src/_plugins  # takes an array of strings and loads plugins in that order
layouts_dir         : src/_layouts
data_dir            : src/_data
includes_dir        : src/_includes
sass:
  sass_dir          : src/_sass

# User defined paths
img                 : /images      # When inserting images, could use "{{site.img}}/path/to/image.png" instead

# 7. Plugins

plugins:            # if "Jekyll::Errors::MissingDependencyException" -> Gem install jekyll-xxx
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-mermaid

# 8. JS version
# Search Plugins on: https://cdnjs.com/
# This is functioned in ./src/_includes/head.html
mathjax_version     : # "3.2.2"
katex_version       : "0.16.9"
mermaid_version     : "11.12.0"
fontawesome_version : "4.6.0"

# 9. kramdown settings
kramdown:
#  parse_block_html: true

# 10. Others
# Cross-Origin Resource Sharing header
webrick:
  headers:
   Access-Control-Allow-Origin: "*"


